name: Test Package

on:
  workflow_dispatch:       # запуск вручную
  #push:
  #  branches:
  #    - master              # или любая тестовая ветка

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        #python-version: ["3.8","3.9","3.10","3.11","3.12","3.13"]
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build hatchling pytest soundfile

    - name: Build package
      run: python -m build --wheel --outdir dist

    - name: Install package
      run: pip install dist/*.whl

    - name: Run tests
      run: pytest tests